### ISSUE TITLE
Please set "code of conduct"

### ISSUE THREAD

**Issue by steffenv-msft** [AzureCAT-GSI/SAP-HANA-ARM#1]
Specify Code of Conduct similar as other projects have in root readme:

Code of Conduct
This project has adopted the Microsoft Open Source Code of Conduct. For more information see the Code of Conduct FAQ or contact opencode@microsoft.com with any additional questions or comments.

**Comment by jgardner04** [comment]
The README has been updated to include a Code of Conduct as mentioned above.
