### ISSUE TITLE
The JRE linked in the setup documentation is newer than the jre used in the hanajb script, jre doesn't get installed on the hanajb VM

### ISSUE THREAD

**Issue by AdamBJ** [AzureCAT-GSI/SAP-HANA-ARM#22]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Description**

The setup documents for this repo (README.md) points to http://www.oracle.com/technetwork/java/javase/downloads/server-jre9-downloads-3848530.html as the location the Windows Server jre should be downloaded from. This results in users downloading jre 9.0.4 (as of Jan 30th, 2018). However, in hanastudio.ps1, 9.0.1 is hard-coded as the java version. When the script is run in the course of creating the hanajb VM, jre is not installed because 9.0.4 != 9.0.1.

**Comment by claudhg9** [comment]
Thanks for the feedback Adam!

**Comment by claudhg9** [comment]
A fix for this bug was applied.

**Comment by mioteg** [comment]
Nice turn around time!

Sent from my phone, please excuse my brevity.

Michiel van Otegem | Senior Program Manager | Azure Partner CAT

________________________________
