### ISSUE TITLE
Mismatch between folder name in docs and hard-coded folder name in scripts

### ISSUE THREAD

**Issue by AdamBJ** [AzureCAT-GSI/SAP-HANA-ARM#26]
BUG REPORT INFORMATION
---------------------------------------------------
**Description**

In the setup documentation, the name of the folder that contains the installation files is given as `SaPBits`. However, in each of the scripts in the `scripts` folder, the argument passed to `wget` is for a folder named `SapBits`. Since Linux is case sensitive, if we follow the guide and create the `SaPBits` folder, the download initiated by the deployment scripts in the `scripts` folder fails, resulting in a Linux VM with no HANA Server installed on it.

**Comment by claudhg9** [comment]
Fixed in the latest release for master.
